// Auto-generated by tools/build_data.py from data/entries.csv — do not edit by hand.
// mariko: 246 rows · erista: 17 rows
window.SPEEDO_DATA = {
  "mariko": [
    {
      "owner": "Happy",
      "model": "OLED",
      "cpu": 1766,
      "gpu": 1796,
      "soc": 1810,
      "ram": "WT:F",
      "notes": "Best GPU/SOC speedo ever recorded. Best known speedo atm."
    },
    {
      "owner": "N/a",
      "model": "OLED",
      "cpu": 1774,
      "gpu": 1792,
      "soc": 1808,
      "ram": "WT:F",
      "notes": "Soc issues, broken. Likely highest known cpu speedo."
    },
    {
      "owner": "N/a",
      "model": "OLED",
      "cpu": 1749,
      "gpu": 1786,
      "soc": 1803,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Meha",
      "model": "OLED",
      "cpu": 1738,
      "gpu": 1755,
      "soc": 1778,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "WinnerBoi77",
      "model": "OLED",
      "cpu": 1720,
      "gpu": 1728,
      "soc": 1760,
      "ram": "NEE",
      "notes": "Extremely good"
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1714,
      "gpu": 1727,
      "soc": 1753,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Souldbminer",
      "model": "OLED",
      "cpu": 1720,
      "gpu": 1726,
      "soc": 1749,
      "ram": "WT:F",
      "notes": "Third best tested console, beats WinnerBoi77's console in GPU UV. Ram is ok though"
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1706,
      "gpu": 1733,
      "soc": 1742,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "Muha",
      "model": "OLED",
      "cpu": 1700,
      "gpu": 1717,
      "soc": 1731,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "Happy",
      "model": "OLED",
      "cpu": 1703,
      "gpu": 1721,
      "soc": 1730,
      "ram": "WT:F",
      "notes": "Please I need average data, too many good units :/"
    },
    {
      "owner": "Shawn Shakir",
      "model": "OLED",
      "cpu": 1688,
      "gpu": 1693,
      "soc": 1728,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1697,
      "gpu": 1707,
      "soc": 1728,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1666,
      "gpu": 1707,
      "soc": 1727,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "tembokbesi",
      "model": "OLED",
      "cpu": 1683,
      "gpu": 1701,
      "soc": 1725,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1692,
      "gpu": 1699,
      "soc": 1725,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1694,
      "gpu": 1718,
      "soc": 1724,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "sylvixor_",
      "model": "OLED",
      "cpu": 1700,
      "gpu": 1702,
      "soc": 1721,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Flopsider",
      "model": "V2",
      "cpu": 1697,
      "gpu": 1714,
      "soc": 1721,
      "ram": "AA-MGCL",
      "notes": "worst AA bin of all time. 2433 not stable at 1-1-1-1-1-1-1-1. CPU is insanely good."
    },
    {
      "owner": "miki130504",
      "model": "OLED",
      "cpu": 1679,
      "gpu": 1689,
      "soc": 1720,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1676,
      "gpu": 1688,
      "soc": 1720,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "kacked",
      "model": "Lite",
      "cpu": 1674,
      "gpu": 1700,
      "soc": 1717,
      "ram": "NME",
      "notes": "Saddest NME ever"
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1705,
      "gpu": 1708,
      "soc": 1717,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "android_pie",
      "model": "OLED",
      "cpu": 1683,
      "gpu": 1717,
      "soc": 1717,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1671,
      "gpu": 1682,
      "soc": 1716,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1684,
      "gpu": 1690,
      "soc": 1715,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "killerbee69",
      "model": "OLED",
      "cpu": 1676,
      "gpu": 1693,
      "soc": 1715,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1656,
      "gpu": 1679,
      "soc": 1714,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1655,
      "gpu": 1683,
      "soc": 1714,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1667,
      "gpu": 1706,
      "soc": 1712,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "josehand1",
      "model": "OLED",
      "cpu": 1656,
      "gpu": 1670,
      "soc": 1711,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1678,
      "gpu": 1687,
      "soc": 1711,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "Xenshen",
      "model": "Lite",
      "cpu": 1666,
      "gpu": 1674,
      "soc": 1710,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1653,
      "gpu": 1681,
      "soc": 1710,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "Tibe",
      "model": "OLED",
      "cpu": 1656,
      "gpu": 1683,
      "soc": 1707,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1671,
      "gpu": 1696,
      "soc": 1707,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Arcdelta",
      "model": "V2",
      "cpu": 1693,
      "gpu": 1688,
      "soc": 1707,
      "ram": "AM-MGCJ",
      "notes": "Weird with timings"
    },
    {
      "owner": "Souldbminer",
      "model": "OLED",
      "cpu": 1677,
      "gpu": 1693,
      "soc": 1706,
      "ram": "AA-MGCL",
      "notes": "Great console"
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1678,
      "gpu": 1684,
      "soc": 1704,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "N/a",
      "model": "OLED",
      "cpu": 1677,
      "gpu": 1689,
      "soc": 1703,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1680,
      "gpu": 1692,
      "soc": 1702,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1676,
      "gpu": 1682,
      "soc": 1702,
      "ram": "AA-MGCL",
      "notes": "My current personal console, WTB unit died of ligma lol"
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1661,
      "gpu": 1674,
      "soc": 1702,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1673,
      "gpu": 1676,
      "soc": 1701,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1667,
      "gpu": 1664,
      "soc": 1701,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1678,
      "gpu": 1693,
      "soc": 1701,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1662,
      "gpu": 1688,
      "soc": 1700,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Dom",
      "model": "OLED",
      "cpu": 1634,
      "gpu": 1690,
      "soc": 1700,
      "ram": "WT:F",
      "notes": "God tier"
    },
    {
      "owner": "Spudgod",
      "model": "OLED",
      "cpu": 1662,
      "gpu": 1689,
      "soc": 1698,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1658,
      "gpu": 1676,
      "soc": 1698,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "nanofix?",
      "model": "Lite",
      "cpu": 1673,
      "gpu": 1684,
      "soc": 1697,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "kaitherikkor0830",
      "model": "OLED",
      "cpu": 1669,
      "gpu": 1676,
      "soc": 1697,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1667,
      "gpu": 1677,
      "soc": 1697,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "Xenshen",
      "model": "Lite",
      "cpu": 1669,
      "gpu": 1677,
      "soc": 1696,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1654,
      "gpu": 1670,
      "soc": 1696,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1662,
      "gpu": 1682,
      "soc": 1696,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1650,
      "gpu": 1672,
      "soc": 1695,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1639,
      "gpu": 1669,
      "soc": 1695,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1677,
      "gpu": 1680,
      "soc": 1692,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1635,
      "gpu": 1669,
      "soc": 1691,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1640,
      "gpu": 1661,
      "soc": 1690,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "kacked",
      "model": "V2",
      "cpu": 1657,
      "gpu": 1661,
      "soc": 1689,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1666,
      "gpu": 1646,
      "soc": 1688,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1637,
      "gpu": 1676,
      "soc": 1688,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1654,
      "gpu": 1672,
      "soc": 1687,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1643,
      "gpu": 1665,
      "soc": 1687,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1623,
      "gpu": 1652,
      "soc": 1686,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1662,
      "gpu": 1673,
      "soc": 1686,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1651,
      "gpu": 1666,
      "soc": 1685,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1626,
      "gpu": 1657,
      "soc": 1685,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "blaise25",
      "model": "V2",
      "cpu": 1638,
      "gpu": 1660,
      "soc": 1685,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "leywinarts",
      "model": "V2",
      "cpu": 1646,
      "gpu": 1668,
      "soc": 1684,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Glazed",
      "model": "OLED",
      "cpu": 1645,
      "gpu": 1650,
      "soc": 1684,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1668,
      "gpu": 1663,
      "soc": 1684,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1651,
      "gpu": 1668,
      "soc": 1684,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1659,
      "gpu": 1655,
      "soc": 1684,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "Xenshen",
      "model": "Lite",
      "cpu": 1623,
      "gpu": 1630,
      "soc": 1683,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1626,
      "gpu": 1655,
      "soc": 1683,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "NaGa?",
      "model": "Lite",
      "cpu": 1651,
      "gpu": 1650,
      "soc": 1681,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1641,
      "gpu": 1668,
      "soc": 1681,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1638,
      "gpu": 1664,
      "soc": 1680,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1640,
      "gpu": 1662,
      "soc": 1680,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1649,
      "gpu": 1668,
      "soc": 1680,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1644,
      "gpu": 1655,
      "soc": 1679,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1671,
      "gpu": 1669,
      "soc": 1679,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "aves",
      "model": "OLED",
      "cpu": 1649,
      "gpu": 1659,
      "soc": 1679,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1642,
      "gpu": 1658,
      "soc": 1678,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1618,
      "gpu": 1638,
      "soc": 1678,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1633,
      "gpu": 1643,
      "soc": 1677,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1615,
      "gpu": 1643,
      "soc": 1677,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1631,
      "gpu": 1655,
      "soc": 1676,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1632,
      "gpu": 1654,
      "soc": 1676,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1639,
      "gpu": 1646,
      "soc": 1675,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1648,
      "gpu": 1661,
      "soc": 1674,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "B3711",
      "model": "OLED",
      "cpu": 1630,
      "gpu": 1661,
      "soc": 1674,
      "ram": "AA-MGCL",
      "notes": "Pretty much the average switch, bossibly the best known AA bin"
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1644,
      "gpu": 1662,
      "soc": 1672,
      "ram": "WT:B",
      "notes": "Went to the gym and now is a 1700 speedo unit. Now this unit is dead"
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1652,
      "gpu": 1662,
      "soc": 1672,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "sidlafkah",
      "model": "OLED",
      "cpu": 1635,
      "gpu": 1656,
      "soc": 1670,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1646,
      "gpu": 1649,
      "soc": 1670,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1641,
      "gpu": 1651,
      "soc": 1670,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "ValiantChaos",
      "model": "OLED",
      "cpu": 1647,
      "gpu": 1652,
      "soc": 1669,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1656,
      "gpu": 1663,
      "soc": 1669,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1629,
      "gpu": 1655,
      "soc": 1669,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "jecksabido",
      "model": "OLED",
      "cpu": 1631,
      "gpu": 1651,
      "soc": 1668,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1625,
      "gpu": 1646,
      "soc": 1668,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1625,
      "gpu": 1649,
      "soc": 1668,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1593,
      "gpu": 1626,
      "soc": 1668,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1630,
      "gpu": 1647,
      "soc": 1668,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "NaGa?",
      "model": "OLED",
      "cpu": 1614,
      "gpu": 1640,
      "soc": 1667,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1654,
      "gpu": 1661,
      "soc": 1667,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1615,
      "gpu": 1648,
      "soc": 1667,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1634,
      "gpu": 1644,
      "soc": 1665,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1647,
      "soc": 1665,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1647,
      "soc": 1665,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "NaGa?",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1635,
      "soc": 1664,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1636,
      "soc": 1664,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1645,
      "gpu": 1640,
      "soc": 1664,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1627,
      "gpu": 1647,
      "soc": 1664,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1631,
      "gpu": 1654,
      "soc": 1664,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "Furredo",
      "model": "OLED",
      "cpu": 1635,
      "gpu": 1646,
      "soc": 1663,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1625,
      "gpu": 1632,
      "soc": 1663,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "Dom",
      "model": "Lite",
      "cpu": 1627,
      "gpu": 1646,
      "soc": 1663,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1611,
      "gpu": 1632,
      "soc": 1662,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1640,
      "gpu": 1642,
      "soc": 1662,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Xenshen",
      "model": "Lite",
      "cpu": 1605,
      "gpu": 1657,
      "soc": 1661,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "jelbo",
      "model": "OLED",
      "cpu": 1607,
      "gpu": 1632,
      "soc": 1661,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1625,
      "gpu": 1649,
      "soc": 1661,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1633,
      "gpu": 1649,
      "soc": 1660,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Anxiety_Timmy",
      "model": "Lite",
      "cpu": 1653,
      "gpu": 1654,
      "soc": 1660,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1630,
      "gpu": 1640,
      "soc": 1659,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1609,
      "gpu": 1635,
      "soc": 1659,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "seman",
      "model": "Lite",
      "cpu": 1641,
      "gpu": 1650,
      "soc": 1658,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1613,
      "gpu": 1632,
      "soc": 1658,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1629,
      "gpu": 1641,
      "soc": 1658,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1604,
      "gpu": 1627,
      "soc": 1658,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1632,
      "gpu": 1646,
      "soc": 1657,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1635,
      "gpu": 1638,
      "soc": 1657,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1625,
      "gpu": 1639,
      "soc": 1657,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1628,
      "gpu": 1644,
      "soc": 1656,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1604,
      "gpu": 1636,
      "soc": 1656,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1631,
      "gpu": 1631,
      "soc": 1656,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "Cheesecake4781",
      "model": "V2",
      "cpu": 1639,
      "gpu": 1643,
      "soc": 1656,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "rodrig0almeida",
      "model": "OLED",
      "cpu": 1622,
      "gpu": 1637,
      "soc": 1655,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1606,
      "gpu": 1643,
      "soc": 1655,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1615,
      "gpu": 1632,
      "soc": 1654,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "Dom",
      "model": "V2",
      "cpu": 1627,
      "gpu": 1647,
      "soc": 1654,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1628,
      "gpu": 1638,
      "soc": 1653,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1625,
      "gpu": 1625,
      "soc": 1653,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1604,
      "gpu": 1620,
      "soc": 1653,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "TDRR",
      "model": "V2",
      "cpu": 1604,
      "gpu": 1634,
      "soc": 1652,
      "ram": "AA-MGCL",
      "notes": "Definition of average"
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1625,
      "gpu": 1632,
      "soc": 1652,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1631,
      "soc": 1652,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1632,
      "gpu": 1646,
      "soc": 1652,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1630,
      "gpu": 1637,
      "soc": 1652,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "Lite",
      "cpu": 1611,
      "gpu": 1636,
      "soc": 1651,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "Tingao",
      "model": "OLED",
      "cpu": 1602,
      "gpu": 1614,
      "soc": 1650,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1611,
      "gpu": 1637,
      "soc": 1650,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1607,
      "gpu": 1639,
      "soc": 1650,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1638,
      "gpu": 1624,
      "soc": 1650,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "taffer",
      "model": "OLED",
      "cpu": 1607,
      "gpu": 1626,
      "soc": 1649,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "kacked",
      "model": "OLED",
      "cpu": 1620,
      "gpu": 1637,
      "soc": 1649,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1601,
      "gpu": 1624,
      "soc": 1649,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1621,
      "gpu": 1632,
      "soc": 1649,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1606,
      "gpu": 1619,
      "soc": 1648,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1622,
      "gpu": 1635,
      "soc": 1647,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1619,
      "gpu": 1630,
      "soc": 1647,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1613,
      "gpu": 1626,
      "soc": 1646,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1630,
      "gpu": 1633,
      "soc": 1646,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1610,
      "gpu": 1633,
      "soc": 1645,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1576,
      "gpu": 1612,
      "soc": 1644,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1609,
      "gpu": 1629,
      "soc": 1644,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1613,
      "gpu": 1625,
      "soc": 1643,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1628,
      "gpu": 1646,
      "soc": 1643,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1596,
      "gpu": 1617,
      "soc": 1643,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1596,
      "gpu": 1617,
      "soc": 1643,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1595,
      "gpu": 1613,
      "soc": 1641,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1594,
      "gpu": 1622,
      "soc": 1640,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1587,
      "gpu": 1597,
      "soc": 1640,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1600,
      "gpu": 1619,
      "soc": 1640,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1617,
      "gpu": 1628,
      "soc": 1639,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1606,
      "gpu": 1629,
      "soc": 1639,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1614,
      "gpu": 1616,
      "soc": 1638,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "nanofix?",
      "model": "OLED",
      "cpu": 1607,
      "gpu": 1616,
      "soc": 1637,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1608,
      "gpu": 1625,
      "soc": 1637,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1576,
      "gpu": 1609,
      "soc": 1637,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1611,
      "gpu": 1618,
      "soc": 1636,
      "ram": "WT:E",
      "notes": ""
    },
    {
      "owner": "nanofix?",
      "model": "OLED",
      "cpu": 1579,
      "gpu": 1607,
      "soc": 1634,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "jelbo",
      "model": "OLED",
      "cpu": 1549,
      "gpu": 1621,
      "soc": 1634,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1607,
      "gpu": 1614,
      "soc": 1634,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1581,
      "gpu": 1582,
      "soc": 1632,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1594,
      "gpu": 1604,
      "soc": 1632,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1594,
      "gpu": 1604,
      "soc": 1632,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "miki130504",
      "model": "Lite",
      "cpu": 1609,
      "gpu": 1609,
      "soc": 1631,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1570,
      "gpu": 1593,
      "soc": 1631,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1580,
      "gpu": 1599,
      "soc": 1631,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "V2",
      "cpu": 1596,
      "gpu": 1617,
      "soc": 1629,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1590,
      "gpu": 1606,
      "soc": 1629,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1588,
      "gpu": 1602,
      "soc": 1629,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1588,
      "gpu": 1602,
      "soc": 1629,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1594,
      "gpu": 1600,
      "soc": 1628,
      "ram": "AA-MGCL",
      "notes": "pretty good RAM bin"
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1594,
      "gpu": 1592,
      "soc": 1628,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1606,
      "gpu": 1623,
      "soc": 1628,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "leafjesus1618",
      "model": "OLED",
      "cpu": 1599,
      "gpu": 1620,
      "soc": 1627,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1580,
      "gpu": 1594,
      "soc": 1626,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1588,
      "gpu": 1609,
      "soc": 1626,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1586,
      "gpu": 1608,
      "soc": 1626,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1595,
      "gpu": 1595,
      "soc": 1624,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1574,
      "gpu": 1599,
      "soc": 1624,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "OLED",
      "cpu": 1597,
      "gpu": 1607,
      "soc": 1623,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "miki130504",
      "model": "OLED",
      "cpu": 1607,
      "gpu": 1611,
      "soc": 1620,
      "ram": "WT:B",
      "notes": "worst wtb bin ever"
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1617,
      "gpu": 1618,
      "soc": 1618,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "Emetsys",
      "model": "Lite",
      "cpu": 1566,
      "gpu": 1596,
      "soc": 1618,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1603,
      "gpu": 1612,
      "soc": 1617,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1571,
      "gpu": 1598,
      "soc": 1617,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "Renzi",
      "model": "OLED",
      "cpu": 1594,
      "gpu": 1607,
      "soc": 1615,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1553,
      "gpu": 1590,
      "soc": 1615,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1601,
      "gpu": 1603,
      "soc": 1614,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1587,
      "gpu": 1594,
      "soc": 1614,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1560,
      "gpu": 1581,
      "soc": 1613,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1574,
      "gpu": 1597,
      "soc": 1613,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1593,
      "gpu": 1585,
      "soc": 1609,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1584,
      "gpu": 1595,
      "soc": 1608,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1568,
      "gpu": 1597,
      "soc": 1608,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1580,
      "gpu": 1579,
      "soc": 1607,
      "ram": "NME",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1583,
      "gpu": 1600,
      "soc": 1605,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "Lite",
      "cpu": 1598,
      "gpu": 1599,
      "soc": 1604,
      "ram": "NME",
      "notes": "Lites take the L"
    },
    {
      "owner": "Spudgod",
      "model": "V2",
      "cpu": 1593,
      "gpu": 1596,
      "soc": 1602,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1558,
      "gpu": 1573,
      "soc": 1601,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1570,
      "gpu": 1571,
      "soc": 1601,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1571,
      "gpu": 1584,
      "soc": 1600,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "miki130504",
      "model": "OLED",
      "cpu": 1552,
      "gpu": 1562,
      "soc": 1590,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1520,
      "gpu": 1552,
      "soc": 1587,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1552,
      "gpu": 1564,
      "soc": 1585,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1552,
      "gpu": 1559,
      "soc": 1585,
      "ram": "WT:B",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1515,
      "gpu": 1544,
      "soc": 1579,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Alvise",
      "model": "OLED",
      "cpu": 1564,
      "gpu": 1570,
      "soc": 1577,
      "ram": "AA-MGCL",
      "notes": "God tier"
    },
    {
      "owner": "Lightos_",
      "model": "V2",
      "cpu": 1499,
      "gpu": 1540,
      "soc": 1574,
      "ram": "AA-MGCL",
      "notes": "Good ram bin."
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1514,
      "gpu": 1547,
      "soc": 1569,
      "ram": "AB-MGCL",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1525,
      "gpu": 1527,
      "soc": 1566,
      "ram": "NEE",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "Lite",
      "cpu": 1524,
      "gpu": 1549,
      "soc": 1551,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "OLED",
      "cpu": 1484,
      "gpu": 1503,
      "soc": 1529,
      "ram": "NEE",
      "notes": "Sadest nee of all time."
    },
    {
      "owner": "evil_santa",
      "model": "V2",
      "cpu": 1496,
      "gpu": 1517,
      "soc": 1523,
      "ram": "AM-MGCJ",
      "notes": ""
    },
    {
      "owner": "N/a",
      "model": "Lite",
      "cpu": 1461,
      "gpu": 1482,
      "soc": 1502,
      "ram": "WT:F",
      "notes": ""
    },
    {
      "owner": "N/a",
      "model": "V2",
      "cpu": 1466,
      "gpu": 1487,
      "soc": 1492,
      "ram": "NME",
      "notes": "Worst Switch Ever, barely passes QC"
    },
    {
      "owner": "yousef",
      "model": "OLED",
      "cpu": 1619,
      "gpu": 1642,
      "soc": 1677,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "yousef",
      "model": "OLED",
      "cpu": 1613,
      "gpu": 1618,
      "soc": 1634,
      "ram": "AA-MGCL",
      "notes": ""
    },
    {
      "owner": "Xenshen",
      "model": "OLED",
      "cpu": 1693,
      "gpu": 1710,
      "soc": 1731,
      "ram": "AM-MGCJ",
      "notes": "Was ram swapped to 8GB"
    }
  ],
  "erista": [
    {
      "owner": "Lightos_",
      "model": "V1",
      "cpu": 2130,
      "gpu": 2132,
      "soc": 1991,
      "ram": "MGCH",
      "notes": "God tier ram"
    },
    {
      "owner": "Souldbminer",
      "model": "V1",
      "cpu": 2130,
      "gpu": 2128,
      "soc": 2025,
      "ram": "MGCH",
      "notes": "Very good bin but a bit funky at high voltages"
    },
    {
      "owner": "Adam",
      "model": "V1",
      "cpu": 2055,
      "gpu": 2058,
      "soc": 1956,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "WinnerBoi77",
      "model": "V1",
      "cpu": 2057,
      "gpu": 2071,
      "soc": 1963,
      "ram": "MGCH",
      "notes": "RIP charging port"
    },
    {
      "owner": "nanofix?",
      "model": "V1",
      "cpu": 2108,
      "gpu": 2118,
      "soc": 1992,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "zyqifana",
      "model": "V1",
      "cpu": 2103,
      "gpu": 2099,
      "soc": 2009,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "jelbo",
      "model": "V1",
      "cpu": 2025,
      "gpu": 2018,
      "soc": 1930,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "V1",
      "cpu": 2116,
      "gpu": 2114,
      "soc": 2002,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "V1",
      "cpu": 2030,
      "gpu": 2021,
      "soc": 1942,
      "ram": "MGCH",
      "notes": "Best MGCH bin ever (2227 at 1175mv)"
    },
    {
      "owner": "Samy",
      "model": "V1",
      "cpu": 2074,
      "gpu": 2058,
      "soc": 1952,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "Samy",
      "model": "V1",
      "cpu": 2052,
      "gpu": 2055,
      "soc": 1933,
      "ram": "MGCH",
      "notes": ""
    },
    {
      "owner": "Manin",
      "model": "V1",
      "cpu": 2024,
      "gpu": 2033,
      "soc": 1967,
      "ram": "MGCH",
      "notes": "Worst ram binning of all time, 2131@???mV (still needs further testing)"
    },
    {
      "owner": "Kwadarth",
      "model": "V1",
      "cpu": 2103,
      "gpu": 2118,
      "soc": 2010,
      "ram": "NLE",
      "notes": ""
    },
    {
      "owner": "Heri",
      "model": "V1",
      "cpu": 2101,
      "gpu": 2101,
      "soc": null,
      "ram": "NLE",
      "notes": "Weird speedo"
    },
    {
      "owner": "AnxietyTimmy",
      "model": "V1",
      "cpu": 2016,
      "gpu": 2006,
      "soc": 1908,
      "ram": "NLE",
      "notes": ""
    },
    {
      "owner": "Chansey",
      "model": "V1",
      "cpu": 2133,
      "gpu": 2147,
      "soc": 2019,
      "ram": "NLE",
      "notes": ""
    },
    {
      "owner": "evil_santa",
      "model": "V1",
      "cpu": 2058,
      "gpu": 2068,
      "soc": 1956,
      "ram": "WT:C",
      "notes": "Only known WT:C"
    }
  ]
};
