#!/usr/bin/env python3
"""Generate data.js from the canonical data/entries.csv.

    python tools/build_data.py

Produces:  window.SPEEDO_DATA = { "mariko": [...], "erista": [...] };
Loaded via a plain <script> tag so it works on GitHub Pages and from file://.
Run this after any change to data/entries.csv (the GitHub Action does this
automatically for issue submissions).
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "entries.csv"
OUT = ROOT / "data.js"


def to_int(value):
    v = (value or "").strip()
    if not v:
        return None
    try:
        return round(float(v.replace(",", ".")))
    except ValueError:
        return None


def main():
    data = {"mariko": [], "erista": []}
    with SRC.open("r", encoding="utf-8-sig", newline="") as fh:
        for row in csv.DictReader(fh):
            platform = (row.get("platform") or "").strip().lower()
            if platform not in data:
                continue
            cpu, gpu, soc = to_int(row.get("cpu")), to_int(row.get("gpu")), to_int(row.get("soc"))
            if cpu is None and gpu is None and soc is None:
                continue
            model = (row.get("model") or "").strip()
            if not model:
                model = "V1" if platform == "erista" else "Unknown"
            data[platform].append({
                "owner": (row.get("owner") or "").strip() or "Anonymous",
                "model": model,
                "cpu": cpu, "gpu": gpu, "soc": soc,
                "ram": (row.get("ram") or "").strip(),
                "notes": (row.get("notes") or "").strip(),
            })

    payload = json.dumps(data, ensure_ascii=False, indent=2)
    banner = (
        "// Auto-generated by tools/build_data.py from data/entries.csv — do not edit by hand.\n"
        f"// mariko: {len(data['mariko'])} rows · erista: {len(data['erista'])} rows\n"
        "window.SPEEDO_DATA = "
    )
    OUT.write_text(banner + payload + ";\n", encoding="utf-8")
    print(f"Wrote mariko={len(data['mariko'])} erista={len(data['erista'])} to {OUT}")


if __name__ == "__main__":
    main()
